# This file was generated by GoReleaser. DO NOT EDIT.
cask "nightshift" do
  name "nightshift"
  desc "Nightshift runs AI maintenance tasks overnight"
  homepage "https://github.com/marcus/nightshift"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nightshift"

  on_macos do
    on_intel do
      url "https://github.com/marcus/nightshift/releases/download/v#{version}/nightshift_#{version}_darwin_amd64.tar.gz"
      sha256 "358b297881fd0fc6a42494e0a428e73f77c14e1271e44a5e3b79a1ea660f3a02"
    end
    on_arm do
      url "https://github.com/marcus/nightshift/releases/download/v#{version}/nightshift_#{version}_darwin_arm64.tar.gz"
      sha256 "4e4c1ae7ccfd1ba3cacec5e5deeaab75884575db332f448b33d9702e23a5de46"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcus/nightshift/releases/download/v#{version}/nightshift_#{version}_linux_amd64.tar.gz"
      sha256 "f1313e307aa91429a8e91e7428cc38dbae1bb2cafc961e8a845091f7ff18e32a"
    end
    on_arm do
      url "https://github.com/marcus/nightshift/releases/download/v#{version}/nightshift_#{version}_linux_arm64.tar.gz"
      sha256 "071ecbf953968264416c0d20816cb9c98000e577f7a534fbcff43a21e79b4295"
    end
  end

  # No zap stanza required
end
