# This file was generated by GoReleaser. DO NOT EDIT.
cask "nightshift" do
  name "nightshift"
  desc "Nightshift runs AI maintenance tasks overnight"
  homepage "https://github.com/marcus/nightshift"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nightshift"

  on_macos do
    on_intel do
      url "https://github.com/marcus/nightshift/releases/download/v#{version}/nightshift_#{version}_darwin_amd64.tar.gz"
      sha256 "ec58066585af4998a92c15efe64eb2c8dc5616b92b8fdc00b45c7df5c81ba876"
    end
    on_arm do
      url "https://github.com/marcus/nightshift/releases/download/v#{version}/nightshift_#{version}_darwin_arm64.tar.gz"
      sha256 "696d5a6c685adf898e885569d7d354d47b1ec3cf554d7388d2fd30f3c4d1504f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcus/nightshift/releases/download/v#{version}/nightshift_#{version}_linux_amd64.tar.gz"
      sha256 "0637e31d78a6838ad277c61a176a37e1df045f2db76353f2da3d4d629513540c"
    end
    on_arm do
      url "https://github.com/marcus/nightshift/releases/download/v#{version}/nightshift_#{version}_linux_arm64.tar.gz"
      sha256 "4b4526b86dd91f456efcd4657ce5ba0e4d81030642687201a1d631bf3cc57669"
    end
  end

  # No zap stanza required
end
