# This file was generated by GoReleaser. DO NOT EDIT.
cask "sidecar" do
  name "sidecar"
  desc "A TUI dashboard for AI coding agents"
  homepage "https://github.com/marcus/sidecar"
  version "0.60.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sidecar"

  on_macos do
    on_intel do
      url "https://github.com/marcus/sidecar/releases/download/v#{version}/sidecar_#{version}_darwin_amd64.tar.gz"
      sha256 "bbc4cc2868b9a8a7ec0552b999f58c11a1bc47d6dad975fbad53f61cac8519f2"
    end
    on_arm do
      url "https://github.com/marcus/sidecar/releases/download/v#{version}/sidecar_#{version}_darwin_arm64.tar.gz"
      sha256 "7a7edfdcc1aaa99eb6d726871e97a54f4e021a4df29aaf9f4260d48e70950b84"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcus/sidecar/releases/download/v#{version}/sidecar_#{version}_linux_amd64.tar.gz"
      sha256 "f63fdd3fc074264de9dcc7f5a066b63d3eefe1d76ed2f01e4252ab7a1773f7fd"
    end
    on_arm do
      url "https://github.com/marcus/sidecar/releases/download/v#{version}/sidecar_#{version}_linux_arm64.tar.gz"
      sha256 "a7efa52ce80a02e737321167f260a539ada8e6612bbc10a93abb1f9325478ce8"
    end
  end

  # No zap stanza required
end
