# This file was generated by GoReleaser. DO NOT EDIT.
cask "sidecar" do
  name "sidecar"
  desc "A TUI dashboard for AI coding agents"
  homepage "https://github.com/marcus/sidecar"
  version "0.67.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sidecar"

  on_macos do
    on_intel do
      url "https://github.com/marcus/sidecar/releases/download/v#{version}/sidecar_#{version}_darwin_amd64.tar.gz"
      sha256 "eb37d6d2c309b708affb81e135f194093b3f6daebc9a6bc1271c1c4ccba27310"
    end
    on_arm do
      url "https://github.com/marcus/sidecar/releases/download/v#{version}/sidecar_#{version}_darwin_arm64.tar.gz"
      sha256 "5eee8b02b499517ab5dd734e8ee3d2afaec6b6ef1bed8068df36fe1f2e7555ec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcus/sidecar/releases/download/v#{version}/sidecar_#{version}_linux_amd64.tar.gz"
      sha256 "188708d988b10f3c80116d7d725c79afcadb159daf1e8f7037d68e6b0f95813f"
    end
    on_arm do
      url "https://github.com/marcus/sidecar/releases/download/v#{version}/sidecar_#{version}_linux_arm64.tar.gz"
      sha256 "826cc878a56d72df83124510a39622fda48a39717b87a3238055e144bd5e4340"
    end
  end

  # No zap stanza required
end
