# This file was generated by GoReleaser. DO NOT EDIT.
cask "td" do
  name "td"
  desc "Task management CLI for AI-assisted development"
  homepage "https://github.com/marcus/td"
  version "0.28.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "td"

  on_macos do
    on_intel do
      url "https://github.com/marcus/td/releases/download/v#{version}/td_#{version}_darwin_amd64.tar.gz"
      sha256 "1b6020380b391d6748fd9706903512671f98049b822e1f6fd3b42dd7023e2c60"
    end
    on_arm do
      url "https://github.com/marcus/td/releases/download/v#{version}/td_#{version}_darwin_arm64.tar.gz"
      sha256 "b502b95c211b9115b82cc20f56d767d5f55657c31213af15bd8dacef95ffd77e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcus/td/releases/download/v#{version}/td_#{version}_linux_amd64.tar.gz"
      sha256 "dd0282985e744065ceb4491c4c48ba1237dc789f2d9be8854ed356a18f189f34"
    end
    on_arm do
      url "https://github.com/marcus/td/releases/download/v#{version}/td_#{version}_linux_arm64.tar.gz"
      sha256 "45f9b04ec958e3cfba18c52cdd2681cef7f13e46c971b7b7b86dabbc2ad43172"
    end
  end

  # No zap stanza required
end
