# This file was generated by GoReleaser. DO NOT EDIT.
cask "td" do
  name "td"
  desc "Task management CLI for AI-assisted development"
  homepage "https://github.com/marcus/td"
  version "0.28.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "td"

  on_macos do
    on_intel do
      url "https://github.com/marcus/td/releases/download/v#{version}/td_#{version}_darwin_amd64.tar.gz"
      sha256 "fa3b21d3b06ac69e16c2d55f3f75f9b35dd3f8e73b5aeacebb72c067bc928758"
    end
    on_arm do
      url "https://github.com/marcus/td/releases/download/v#{version}/td_#{version}_darwin_arm64.tar.gz"
      sha256 "22d6d39bced26699686d991b23d189340bf86152dce16b79610af34460f29b4b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcus/td/releases/download/v#{version}/td_#{version}_linux_amd64.tar.gz"
      sha256 "43b1bb2941c2dfc774e8252ef069ac64180b5e58ec2a422135f4d7b909c31ac6"
    end
    on_arm do
      url "https://github.com/marcus/td/releases/download/v#{version}/td_#{version}_linux_arm64.tar.gz"
      sha256 "3edae3c317ad2545de6cccef25d363279f8dc387900347901ae86460820f13f2"
    end
  end

  # No zap stanza required
end
