# This file was generated by GoReleaser. DO NOT EDIT.
cask "td" do
  name "td"
  desc "Task management CLI for AI-assisted development"
  homepage "https://github.com/marcus/td"
  version "0.31.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "td"

  on_macos do
    on_intel do
      url "https://github.com/marcus/td/releases/download/v#{version}/td_#{version}_darwin_amd64.tar.gz"
      sha256 "86266fbe13ccd673c9ffed9b5c459e514455948748a62970112175063d09768c"
    end
    on_arm do
      url "https://github.com/marcus/td/releases/download/v#{version}/td_#{version}_darwin_arm64.tar.gz"
      sha256 "f6365529b227c2b50a3d170653e1b14f8c594cf203306d7e77d92712c9102760"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcus/td/releases/download/v#{version}/td_#{version}_linux_amd64.tar.gz"
      sha256 "9dc600ed878e12ab9e92368a9e7e8f952554f726dd7e7b3fd511aea1829293d0"
    end
    on_arm do
      url "https://github.com/marcus/td/releases/download/v#{version}/td_#{version}_linux_arm64.tar.gz"
      sha256 "ed51b04703ef360415746704718de1a2812c69d79f286b2be9f053c05dd9f1fa"
    end
  end

  # No zap stanza required
end
