# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sidecar < Formula
  desc "A TUI dashboard for AI coding agents"
  homepage "https://github.com/marcus/sidecar"
  version "0.69.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcus/sidecar/releases/download/v0.69.0/sidecar_0.69.0_darwin_amd64.tar.gz"
      sha256 "b38c9fdbf14eb0882b14d45972e605e02090095cd005b23a02788e333a29be2e"

      def install
        bin.install "sidecar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcus/sidecar/releases/download/v0.69.0/sidecar_0.69.0_darwin_arm64.tar.gz"
      sha256 "7420934ba7dad0a32df2a97443962518433e3a564915dfc775e16ea2abfa9b91"

      def install
        bin.install "sidecar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcus/sidecar/releases/download/v0.69.0/sidecar_0.69.0_linux_amd64.tar.gz"
      sha256 "ffefb53b7f6f6acd1798af7ec370053ee278a563b8e73e4d4979a4f4a7963d23"
      def install
        bin.install "sidecar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcus/sidecar/releases/download/v0.69.0/sidecar_0.69.0_linux_arm64.tar.gz"
      sha256 "174a127e623bd191dc95c0f1eb0de833e51b602362edc07541702a79c8a33ccd"
      def install
        bin.install "sidecar"
      end
    end
  end

  test do
    system "#{bin}/sidecar", "--version"
  end
end
